/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_M_S;

/**
 *
 * @author 88017
 */
public class Restaurant extends javax.swing.JFrame {
    double firstnum;
    double secondnum;
    double result;
    String operations;
    int[]i = new int[15];
    
    /**
     * Creates new form Restaurant
     */
    public Restaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jChickenMomo = new javax.swing.JCheckBox();
        jChickPizza = new javax.swing.JCheckBox();
        jChickenBurger = new javax.swing.JCheckBox();
        jOvenBakedPasta = new javax.swing.JCheckBox();
        jPotatoWed = new javax.swing.JCheckBox();
        jtxtChickBurger = new javax.swing.JTextField();
        jtxtChickPizza = new javax.swing.JTextField();
        jtxtOvenBakedPasta = new javax.swing.JTextField();
        jtxtPotatoWed = new javax.swing.JTextField();
        jtxtChickenMomo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jbtnarrow = new javax.swing.JButton();
        jbtnc = new javax.swing.JButton();
        jbtnPlusdiv = new javax.swing.JButton();
        jbtnplus = new javax.swing.JButton();
        jbtnmin = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtnmul = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtndev = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnpoint = new javax.swing.JButton();
        jbtneq = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jcmbDrinks = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jCTax = new javax.swing.JCheckBox();
        jCDelivery = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jChickBiri = new javax.swing.JCheckBox();
        jMuttonBiri = new javax.swing.JCheckBox();
        jLemonRice = new javax.swing.JCheckBox();
        jGrillNun = new javax.swing.JCheckBox();
        jFriedRice = new javax.swing.JCheckBox();
        jtxtChickBiri = new javax.swing.JTextField();
        jtxtMuttonBiri = new javax.swing.JTextField();
        jtxtFriedRice = new javax.swing.JTextField();
        jtxtGrillNun = new javax.swing.JTextField();
        jtxtLemonRice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jbtnTotal = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnexit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jlblCostOfDelivery = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlblCostOfDrinks = new javax.swing.JLabel();
        jlblCostOfMeal = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTax = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setIconImages(null);

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 204, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Rajosri's Kitchen");

        jPanel1.setLayout(null);

        jChickenMomo.setBackground(new java.awt.Color(255, 204, 153));
        jChickenMomo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChickenMomo.setForeground(new java.awt.Color(255, 255, 255));
        jChickenMomo.setText("Chicken Momos");
        jChickenMomo.setBorderPainted(true);
        jChickenMomo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChickenMomoMouseClicked(evt);
            }
        });
        jPanel1.add(jChickenMomo);
        jChickenMomo.setBounds(20, 260, 250, 30);

        jChickPizza.setBackground(new java.awt.Color(255, 204, 153));
        jChickPizza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChickPizza.setForeground(new java.awt.Color(255, 255, 255));
        jChickPizza.setText("Chicken Pizza");
        jChickPizza.setBorderPainted(true);
        jChickPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChickPizzaMouseClicked(evt);
            }
        });
        jChickPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChickPizzaActionPerformed(evt);
            }
        });
        jPanel1.add(jChickPizza);
        jChickPizza.setBounds(20, 110, 250, 30);

        jChickenBurger.setBackground(new java.awt.Color(255, 204, 153));
        jChickenBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChickenBurger.setForeground(new java.awt.Color(255, 255, 255));
        jChickenBurger.setText("Chicken Cheesy Burger");
        jChickenBurger.setBorderPainted(true);
        jChickenBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChickenBurgerMouseClicked(evt);
            }
        });
        jChickenBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChickenBurgerActionPerformed(evt);
            }
        });
        jPanel1.add(jChickenBurger);
        jChickenBurger.setBounds(20, 60, 250, 30);

        jOvenBakedPasta.setBackground(new java.awt.Color(255, 204, 153));
        jOvenBakedPasta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jOvenBakedPasta.setForeground(new java.awt.Color(255, 255, 255));
        jOvenBakedPasta.setText("Oven Baked Pasta");
        jOvenBakedPasta.setBorderPainted(true);
        jOvenBakedPasta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOvenBakedPastaMouseClicked(evt);
            }
        });
        jPanel1.add(jOvenBakedPasta);
        jOvenBakedPasta.setBounds(20, 160, 250, 30);

        jPotatoWed.setBackground(new java.awt.Color(255, 204, 153));
        jPotatoWed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPotatoWed.setForeground(new java.awt.Color(255, 255, 255));
        jPotatoWed.setText("Potato Wedges");
        jPotatoWed.setBorderPainted(true);
        jPotatoWed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPotatoWedMouseClicked(evt);
            }
        });
        jPanel1.add(jPotatoWed);
        jPotatoWed.setBounds(20, 210, 250, 30);

        jtxtChickBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickBurger.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(jtxtChickBurger);
        jtxtChickBurger.setBounds(350, 60, 140, 28);

        jtxtChickPizza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickPizza.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(jtxtChickPizza);
        jtxtChickPizza.setBounds(350, 110, 140, 28);

        jtxtOvenBakedPasta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtOvenBakedPasta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(jtxtOvenBakedPasta);
        jtxtOvenBakedPasta.setBounds(350, 160, 140, 28);

        jtxtPotatoWed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPotatoWed.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(jtxtPotatoWed);
        jtxtPotatoWed.setBounds(350, 210, 140, 28);

        jtxtChickenMomo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenMomo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(jtxtChickenMomo);
        jtxtChickenMomo.setBounds(350, 260, 140, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fast Food");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 10, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\6th Semester\\CSE 236 Software Development Lab II\\RestaurantManagementSystem\\image\\1.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 510, 320);

        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jtxtDisplay.setEditable(false);
        jtxtDisplay.setBackground(new java.awt.Color(51, 51, 51));
        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.setText("0");

        jbtnarrow.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnarrow.setText("←");
        jbtnarrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnarrowActionPerformed(evt);
            }
        });

        jbtnc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnc.setText("C");
        jbtnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncActionPerformed(evt);
            }
        });

        jbtnPlusdiv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPlusdiv.setText("+/-");
        jbtnPlusdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusdivActionPerformed(evt);
            }
        });

        jbtnplus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnplus.setText("+");
        jbtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusActionPerformed(evt);
            }
        });

        jbtnmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnmin.setText("-");
        jbtnmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnminActionPerformed(evt);
            }
        });

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtnmul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnmul.setText("*");
        jbtnmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmulActionPerformed(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtndev.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtndev.setText("/");
        jbtndev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndevActionPerformed(evt);
            }
        });

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtnpoint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnpoint.setText(".");
        jbtnpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpointActionPerformed(evt);
            }
        });

        jbtneq.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtneq.setText("=");
        jbtneq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jbtnarrow, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jbtnc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnPlusdiv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtneq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnplus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnmin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtndev, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnarrow, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPlusdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnmin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndev, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtneq, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calculator", jPanel3);

        jtxtReceipt.setBackground(new java.awt.Color(255, 204, 153));
        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Receipt", jPanel4);

        jPanel2.add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 20, 350, 570);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\6th Semester\\CSE 236 Software Development Lab II\\RestaurantManagementSystem\\image\\6.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 385, 611);

        jPanel5.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Drinks");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(20, 10, 190, 30);

        jcmbDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbDrinks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cocacola", "Tea", "Coffee", "Cold_Coffee", "Juice" }));
        jcmbDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbDrinksActionPerformed(evt);
            }
        });
        jPanel5.add(jcmbDrinks);
        jcmbDrinks.setBounds(350, 10, 140, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\6th Semester\\CSE 236 Software Development Lab II\\RestaurantManagementSystem\\image\\3.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(0, 0, 510, 50);

        jPanel6.setLayout(null);

        jCTax.setBackground(new java.awt.Color(255, 204, 153));
        jCTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCTax.setForeground(new java.awt.Color(255, 255, 255));
        jCTax.setText("Tax");
        jCTax.setBorderPainted(true);
        jCTax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCTaxMouseClicked(evt);
            }
        });
        jCTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTaxActionPerformed(evt);
            }
        });
        jPanel6.add(jCTax);
        jCTax.setBounds(20, 10, 180, 30);

        jCDelivery.setBackground(new java.awt.Color(255, 204, 153));
        jCDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCDelivery.setForeground(new java.awt.Color(255, 255, 255));
        jCDelivery.setText("Home Delivery");
        jCDelivery.setBorderPainted(true);
        jCDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCDeliveryMouseClicked(evt);
            }
        });
        jPanel6.add(jCDelivery);
        jCDelivery.setBounds(250, 10, 180, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\6th Semester\\CSE 236 Software Development Lab II\\RestaurantManagementSystem\\image\\3.jpg")); // NOI18N
        jLabel9.setText("jLabel6");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(0, 0, 450, 50);

        jPanel7.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Meals");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(160, 10, 100, 30);

        jChickBiri.setBackground(new java.awt.Color(255, 204, 153));
        jChickBiri.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChickBiri.setForeground(new java.awt.Color(255, 255, 255));
        jChickBiri.setText("Chicken Biriyani");
        jChickBiri.setBorderPainted(true);
        jChickBiri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChickBiriMouseClicked(evt);
            }
        });
        jPanel7.add(jChickBiri);
        jChickBiri.setBounds(20, 60, 190, 30);

        jMuttonBiri.setBackground(new java.awt.Color(255, 204, 153));
        jMuttonBiri.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMuttonBiri.setForeground(new java.awt.Color(255, 255, 255));
        jMuttonBiri.setText("Mutton Biriyani");
        jMuttonBiri.setBorderPainted(true);
        jMuttonBiri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMuttonBiriMouseClicked(evt);
            }
        });
        jPanel7.add(jMuttonBiri);
        jMuttonBiri.setBounds(20, 110, 190, 30);

        jLemonRice.setBackground(new java.awt.Color(255, 204, 153));
        jLemonRice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLemonRice.setForeground(new java.awt.Color(255, 255, 255));
        jLemonRice.setText("Lemon Rice");
        jLemonRice.setBorderPainted(true);
        jLemonRice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLemonRiceMouseClicked(evt);
            }
        });
        jLemonRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLemonRiceActionPerformed(evt);
            }
        });
        jPanel7.add(jLemonRice);
        jLemonRice.setBounds(20, 260, 190, 30);

        jGrillNun.setBackground(new java.awt.Color(255, 204, 153));
        jGrillNun.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jGrillNun.setForeground(new java.awt.Color(255, 255, 255));
        jGrillNun.setText("Grill-Nun");
        jGrillNun.setBorderPainted(true);
        jGrillNun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGrillNunMouseClicked(evt);
            }
        });
        jPanel7.add(jGrillNun);
        jGrillNun.setBounds(20, 210, 190, 30);

        jFriedRice.setBackground(new java.awt.Color(255, 204, 153));
        jFriedRice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFriedRice.setForeground(new java.awt.Color(255, 255, 255));
        jFriedRice.setText("Fried Rice");
        jFriedRice.setBorderPainted(true);
        jFriedRice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFriedRiceMouseClicked(evt);
            }
        });
        jPanel7.add(jFriedRice);
        jFriedRice.setBounds(20, 160, 190, 30);

        jtxtChickBiri.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickBiri.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel7.add(jtxtChickBiri);
        jtxtChickBiri.setBounds(270, 60, 140, 28);

        jtxtMuttonBiri.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtMuttonBiri.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel7.add(jtxtMuttonBiri);
        jtxtMuttonBiri.setBounds(270, 110, 140, 28);

        jtxtFriedRice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFriedRice.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel7.add(jtxtFriedRice);
        jtxtFriedRice.setBounds(270, 160, 140, 28);

        jtxtGrillNun.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtGrillNun.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel7.add(jtxtGrillNun);
        jtxtGrillNun.setBounds(270, 210, 140, 28);

        jtxtLemonRice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtLemonRice.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel7.add(jtxtLemonRice);
        jtxtLemonRice.setBounds(270, 260, 140, 28);

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\6th Semester\\CSE 236 Software Development Lab II\\RestaurantManagementSystem\\image\\2.png")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(0, 0, 450, 320);

        jPanel8.setLayout(null);

        jbtnTotal.setBackground(new java.awt.Color(255, 204, 153));
        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnTotalMouseClicked(evt);
            }
        });
        jPanel8.add(jbtnTotal);
        jbtnTotal.setBounds(80, 10, 100, 40);

        jbtnReceipt.setBackground(new java.awt.Color(255, 204, 153));
        jbtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnReceipt.setText("Receipt");
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnReceipt);
        jbtnReceipt.setBounds(310, 11, 100, 40);

        jbtnReset.setBackground(new java.awt.Color(255, 204, 153));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnResetMouseClicked(evt);
            }
        });
        jPanel8.add(jbtnReset);
        jbtnReset.setBounds(550, 11, 100, 40);

        jbtnexit.setBackground(new java.awt.Color(255, 204, 153));
        jbtnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnexit.setText("Exit");
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnexit);
        jbtnexit.setBounds(770, 11, 100, 40);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon("E:\\6th Semester\\CSE 236 Software Development Lab II\\RestaurantManagementSystem\\image\\5.jpg")); // NOI18N
        jLabel12.setText("Total");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(0, 0, 970, 63);

        jPanel10.setLayout(null);

        jlblCostOfDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostOfDelivery.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(jlblCostOfDelivery);
        jlblCostOfDelivery.setBounds(310, 90, 180, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cost Of Meal");
        jPanel10.add(jLabel14);
        jLabel14.setBounds(20, 56, 180, 26);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cost Of Delivery");
        jPanel10.add(jLabel15);
        jLabel15.setBounds(20, 90, 180, 26);

        jlblCostOfDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostOfDrinks.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(jlblCostOfDrinks);
        jlblCostOfDrinks.setBounds(310, 20, 180, 30);

        jlblCostOfMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostOfMeal.setForeground(new java.awt.Color(255, 255, 255));
        jlblCostOfMeal.setText("0");
        jPanel10.add(jlblCostOfMeal);
        jlblCostOfMeal.setBounds(310, 56, 180, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Cost Of Drinks");
        jPanel10.add(jLabel21);
        jLabel21.setBounds(20, 20, 180, 26);

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\6th Semester\\CSE 236 Software Development Lab II\\RestaurantManagementSystem\\image\\4.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel10.add(jLabel4);
        jLabel4.setBounds(0, 0, 510, 130);

        jPanel11.setLayout(null);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Sub Total");
        jPanel11.add(jLabel16);
        jLabel16.setBounds(20, 20, 180, 30);

        jTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTax.setForeground(new java.awt.Color(255, 255, 255));
        jTax.setText("Tax");
        jTax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTaxMouseClicked(evt);
            }
        });
        jPanel11.add(jTax);
        jTax.setBounds(20, 56, 180, 26);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Total");
        jPanel11.add(jLabel18);
        jLabel18.setBounds(20, 90, 180, 26);

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(jlblSubTotal);
        jlblSubTotal.setBounds(260, 20, 180, 26);

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(jlblTax);
        jlblTax.setBounds(260, 56, 180, 30);

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(jlblTotal);
        jlblTotal.setBounds(260, 90, 180, 26);

        jLabel11.setIcon(new javax.swing.ImageIcon("E:\\6th Semester\\CSE 236 Software Development Lab II\\RestaurantManagementSystem\\image\\4.png")); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel11.add(jLabel11);
        jLabel11.setBounds(0, 0, 450, 130);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 1377, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(473, 473, 473))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnminActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="-";
    }//GEN-LAST:event_jbtnminActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText() + jbtn7.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText() + jbtn8.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText() + jbtn9.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText() + jbtn4.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText() + jbtn5.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText() + jbtn6.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText() + jbtn1.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText() + jbtn2.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText() + jbtn3.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText() + jbtn0.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncActionPerformed
        // TODO add your handling code here:
        jtxtDisplay.setText(null);
    }//GEN-LAST:event_jbtncActionPerformed

    private void jbtnarrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnarrowActionPerformed
        // TODO add your handling code here:
        String backspace=null;
        if(jtxtDisplay.getText().length() > 0)
        {
            StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
            strB.deleteCharAt(jtxtDisplay.getText().length() - 1);
            backspace = strB.toString();
            jtxtDisplay.setText(backspace);
        }
    }//GEN-LAST:event_jbtnarrowActionPerformed

    private void jbtndevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndevActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="/";
    }//GEN-LAST:event_jbtndevActionPerformed

    private void jbtnmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmulActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="*";
    }//GEN-LAST:event_jbtnmulActionPerformed

    private void jbtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="+";
    }//GEN-LAST:event_jbtnplusActionPerformed

    private void jbtnpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpointActionPerformed
        // TODO add your handling code here:
        jtxtDisplay.setText(jtxtDisplay.getText()+ jbtnpoint.getText());
    }//GEN-LAST:event_jbtnpointActionPerformed

    private void jbtnPlusdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusdivActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = ops*(-1);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnPlusdivActionPerformed

    private void jbtneqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneqActionPerformed
        // TODO add your handling code here:
        String answer;
        secondnum = Double.parseDouble(jtxtDisplay.getText());
        if(operations == "+")
        {
            result = firstnum + secondnum;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }
        else if(operations == "-")
        {
            result = firstnum - secondnum;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }
        else if(operations == "*")
        {
            result = firstnum * secondnum;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }
        else if(operations == "/")
        {
            result = firstnum / secondnum;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }
    }//GEN-LAST:event_jbtneqActionPerformed

    private void jLemonRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLemonRiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLemonRiceActionPerformed

    private void jCTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTaxActionPerformed

    private void jcmbDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbDrinksActionPerformed
        // TODO add your handling code here:
        int Cocacola = 30;
        int Tea = 15;
        int Coffee = 60;
        int Cold_Coffee = 80;
        int Juice = 50;
        if(jcmbDrinks.getSelectedItem().equals("Cocacola"))
        {
            String d1 = String.format("%d", Cocacola);
            jlblCostOfDrinks.setText(d1);
        }
         if(jcmbDrinks.getSelectedItem().equals("Tea"))
        {
            String d2 = String.format("%d", Tea);
            jlblCostOfDrinks.setText(d2);
        }
          if(jcmbDrinks.getSelectedItem().equals("Coffee"))
        {
            String d3 = String.format("%d", Coffee);
            jlblCostOfDrinks.setText(d3);
        }
           if(jcmbDrinks.getSelectedItem().equals("Cold_Coffee"))
        {
            String d4 = String.format("%d", Cold_Coffee);
            jlblCostOfDrinks.setText(d4);
        }
            if(jcmbDrinks.getSelectedItem().equals("Juice"))
        {
            String d5 = String.format("%d", Juice);
            jlblCostOfDrinks.setText(d5);
        }
    }//GEN-LAST:event_jcmbDrinksActionPerformed

    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jCDeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCDeliveryMouseClicked
        // TODO add your handling code here:
        int delivery = 20;
        if(jCDelivery.isSelected())
        {
            String pdelivery = String.format("%d", delivery);
            jlblCostOfDelivery.setText(pdelivery);
        }
        else
            {
            jlblCostOfDelivery.setText(null);
        }
    }//GEN-LAST:event_jCDeliveryMouseClicked

    private void jbtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnResetMouseClicked

    jlblCostOfDelivery.setText(null);
    jlblCostOfDrinks.setText(null);
    jlblCostOfMeal.setText(null);
    jlblSubTotal.setText(null);
    jlblTax.setText(null);
    jlblTotal.setText(null);
    }//GEN-LAST:event_jbtnResetMouseClicked

    private void jChickenBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChickenBurgerMouseClicked
        // TODO add your handling code here:
        int iChickBurger = 150;
        int ChickBurger = Integer.parseInt(jtxtChickBurger.getText());
        int cMeal = Integer.parseInt(jlblCostOfMeal.getText());
        if(jChickenBurger.isSelected())
        {   
            i[0] = (ChickBurger*iChickBurger)+cMeal;
            String pMeal;
            pMeal = String.format("%d", i[0]);
            jlblCostOfMeal.setText(pMeal);
        }
        
    }//GEN-LAST:event_jChickenBurgerMouseClicked

    private void jChickPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChickPizzaMouseClicked
        // TODO add your handling code here:
        int iChickPizza = 200;
        int ChickPizza = Integer.parseInt(jtxtChickPizza.getText());
        int cMeal = Integer.parseInt(jlblCostOfMeal.getText());
        if(jChickPizza.isSelected())
        {   
            i[1] = (ChickPizza*iChickPizza) + cMeal;
            String pMeal;
            pMeal = String.format("%d", i[1]);
            jlblCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jChickPizzaMouseClicked

    private void jOvenBakedPastaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOvenBakedPastaMouseClicked
        // TODO add your handling code here:
       int iOvenBakedPasta = 100;
        int OvenBakedPasta = Integer.parseInt(jtxtOvenBakedPasta.getText());
        int cMeal = Integer.parseInt(jlblCostOfMeal.getText());
        if(jOvenBakedPasta.isSelected())
        {   
            i[2] = (OvenBakedPasta*iOvenBakedPasta) + cMeal;
            String pMeal;
            pMeal = String.format("%d", i[2]);
            jlblCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jOvenBakedPastaMouseClicked

    private void jChickenBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChickenBurgerActionPerformed
        // TODO add your handling code here:
        /*   double ChickBurger = Double.parseDouble(jtxtChickBurger.getText());
        double cMeal = Double.parseDouble(jlblCostOfMeal.getText());
        double iChickBurger = 150;
        
        if(jChickenBurger.isSelected())
        {
            i[0] = (ChickBurger*iChickBurger)+cMeal;
            String pMeal = String.format("%.2f Tk", i[0]);
            jlblCostOfMeal.setText(pMeal);
        }
        */
    }//GEN-LAST:event_jChickenBurgerActionPerformed

    private void jbtnTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTotalMouseClicked
        // TODO add your handling code here:
        int cTotal1 = Integer.parseInt(jlblCostOfDrinks.getText());
        int cTotal2 = Integer.parseInt(jlblCostOfMeal.getText());
        int cTotal3 = Integer.parseInt(jlblCostOfDelivery.getText());
        int cTotal4 = Integer.parseInt(jlblTax.getText());
        
          
        int SubTotal = (cTotal1+ cTotal2 +cTotal3);
        String iSubTotal = String.format("%d", SubTotal);
        jlblSubTotal.setText(iSubTotal);
        
        int Total = (cTotal1+ cTotal2 +cTotal3 + cTotal4 );
        String iTotal = String.format("%d", Total);
        jlblTotal.setText(iTotal);
        
        String iTaxTotal = String.format("%d", cTotal4);
        jlblTax.setText(iTaxTotal);
          
        
    }//GEN-LAST:event_jbtnTotalMouseClicked

    private void jPotatoWedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPotatoWedMouseClicked
        // TODO add your handling code here:
        int iPotatoWed = 60;
        int PotatoWed = Integer.parseInt(jtxtPotatoWed.getText());
        int cMeal = Integer.parseInt(jlblCostOfMeal.getText());
        if(jPotatoWed.isSelected())
        {   
            i[3] = (PotatoWed*iPotatoWed) + cMeal;
            String pMeal;
            pMeal = String.format("%d", i[3]);
            jlblCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jPotatoWedMouseClicked

    private void jChickenMomoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChickenMomoMouseClicked
        // TODO add your handling code here:
         int iChickenMomo = 160;
        int ChickenMomo = Integer.parseInt(jtxtChickenMomo.getText());
        int cMeal = Integer.parseInt(jlblCostOfMeal.getText());
        if(jChickenMomo.isSelected())
        {   
            i[4] = (ChickenMomo*iChickenMomo) + cMeal;
            String pMeal;
            pMeal = String.format("%d", i[4]);
            jlblCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jChickenMomoMouseClicked

    private void jChickBiriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChickBiriMouseClicked
        // TODO add your handling code here:
          int iChickBiri = 140;
        int ChickBiri = Integer.parseInt(jtxtChickBiri.getText());
        int cMeal = Integer.parseInt(jlblCostOfMeal.getText());
        if(jChickBiri.isSelected())
        {   
            i[5] = (ChickBiri*iChickBiri) + cMeal;
            String pMeal;
            pMeal = String.format("%d", i[5]);
            jlblCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jChickBiriMouseClicked

    private void jMuttonBiriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMuttonBiriMouseClicked
        // TODO add your handling code here:
        int iMuttonBiri = 180;
        int MuttonBiri = Integer.parseInt(jtxtMuttonBiri.getText());
        int cMeal = Integer.parseInt(jlblCostOfMeal.getText());
        if(jMuttonBiri.isSelected())
        {   
            i[6] = (MuttonBiri*iMuttonBiri) + cMeal;
            String pMeal;
            pMeal = String.format("%d", i[6]);
            jlblCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jMuttonBiriMouseClicked

    private void jFriedRiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFriedRiceMouseClicked
        // TODO add your handling code here:
        int iFriedRice = 120;
        int FriedRice = Integer.parseInt(jtxtFriedRice.getText());
        int cMeal = Integer.parseInt(jlblCostOfMeal.getText());
        if(jFriedRice.isSelected())
        {   
            i[7] = (FriedRice*iFriedRice) + cMeal;
            String pMeal;
            pMeal = String.format("%d", i[7]);
            jlblCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jFriedRiceMouseClicked

    private void jGrillNunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGrillNunMouseClicked
        // TODO add your handling code here:
        int iGrillNun = 160;
        int GrillNun = Integer.parseInt(jtxtGrillNun.getText());
        int cMeal = Integer.parseInt(jlblCostOfMeal.getText());
        if(jGrillNun.isSelected())
        {   
            i[8] = (GrillNun*iGrillNun) + cMeal;
            String pMeal;
            pMeal = String.format("%d", i[8]);
            jlblCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jGrillNunMouseClicked

    private void jLemonRiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLemonRiceMouseClicked
        // TODO add your handling code here:
        int iLemonRice = 130;
        int LemonRice = Integer.parseInt(jtxtLemonRice.getText());
        int cMeal = Integer.parseInt(jlblCostOfMeal.getText());
        if(jLemonRice.isSelected())
        {   
            i[9] = (LemonRice*iLemonRice) + cMeal;
            String pMeal;
            pMeal = String.format("%d", i[9]);
            jlblCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jLemonRiceMouseClicked

    private void jTaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaxMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jTaxMouseClicked

    private void jCTaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCTaxMouseClicked
        // TODO add your handling code here:
         if(jCTax.isSelected())
        {
            int cTotal1 = Integer.parseInt(jlblCostOfDrinks.getText());
            int cTotal2 = Integer.parseInt(jlblCostOfMeal.getText());
            int cTotal3 = Integer.parseInt(jlblCostOfDelivery.getText());
            
            int Tax = (cTotal1+ cTotal2 +cTotal3)/100;
            
            String iTax = String.format("%d", Tax);
            jlblTax.setText(iTax);
        }
    }//GEN-LAST:event_jCTaxMouseClicked

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed
        // TODO add your handling code here:
        int Q1 = Integer.parseInt(jtxtChickBurger.getText());
        int Q2 = Integer.parseInt(jtxtChickPizza.getText());
        int Q3 = Integer.parseInt(jtxtOvenBakedPasta.getText());
        int Q4 = Integer.parseInt(jtxtPotatoWed.getText());
        int Q5 = Integer.parseInt(jtxtChickenMomo.getText());
        int Q6 = Integer.parseInt(jtxtChickBiri.getText());
        int Q7 = Integer.parseInt(jtxtMuttonBiri.getText());
        int Q8 = Integer.parseInt(jtxtFriedRice.getText());
        int Q9 = Integer.parseInt(jtxtGrillNun.getText());
        int Q10 = Integer.parseInt(jtxtLemonRice.getText());
        int cTotal1 = Integer.parseInt(jlblCostOfDrinks.getText());
        int cTotal2 = Integer.parseInt(jlblCostOfMeal.getText());
        int cTotal3 = Integer.parseInt(jlblCostOfDelivery.getText());
        int cTotal4 = Integer.parseInt(jlblTax.getText());
        int Total = (cTotal1+ cTotal2 +cTotal3 + cTotal4 );
        
        jtxtReceipt.append("\t  Rajosri's Kitchen\n" + "\t*******************\n\n"
                                                     + "Chicken Cheesy Burger : "+ Q1+" X 150 \n" 
                                                     + "Chicken Pizza         : "+ Q2+" X 200 \n"
                                                     + "Oven Baked Pasta      : "+ Q3+" X 100 \n"
                                                     + "Potato Wedges         : "+ Q4+" X 60  \n"
                                                     + "Chicken Momos         : "+ Q5+" X 160 \n"
                                                     + "Chicken Biriyan       : "+ Q6+" X 140 \n"
                                                     + "Mutton Biriyani       : "+ Q7+" X 180 \n"
                                                     + "Fried Rice            : "+ Q8+" X 120 \n"
                                                     + "Grill-Nun             : "+ Q9+" X 160 \n"
                                                     + "Lemon Rice            : "+ Q10+" X 130\n"
                                                     + "-------------------------------------\n"
                                                     + "Cost Of Meal          : "+ cTotal2 + "Tk \n"
                                                     + "Cost Of Drinks        : "+ cTotal1 + "Tk \n"
                                                     + "Cost Of Delivery      : "+ cTotal3 + "Tk \n"
                                                     + "Tax                       : "+ cTotal4 + "Tk \n"
                                                     + "-------------------------------------\n"
                                                     + "Total                 : "+ Total + "Tk \n");
        
        
    }//GEN-LAST:event_jbtnReceiptActionPerformed

    private void jChickPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChickPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChickPizzaActionPerformed
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Restaurant().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCDelivery;
    private javax.swing.JCheckBox jCTax;
    private javax.swing.JCheckBox jChickBiri;
    private javax.swing.JCheckBox jChickPizza;
    private javax.swing.JCheckBox jChickenBurger;
    private javax.swing.JCheckBox jChickenMomo;
    private javax.swing.JCheckBox jFriedRice;
    private javax.swing.JCheckBox jGrillNun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox jLemonRice;
    private javax.swing.JCheckBox jMuttonBiri;
    private javax.swing.JCheckBox jOvenBakedPasta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JCheckBox jPotatoWed;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jTax;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnPlusdiv;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JButton jbtnarrow;
    private javax.swing.JButton jbtnc;
    private javax.swing.JButton jbtndev;
    private javax.swing.JButton jbtneq;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnmin;
    private javax.swing.JButton jbtnmul;
    private javax.swing.JButton jbtnplus;
    private javax.swing.JButton jbtnpoint;
    private javax.swing.JComboBox<String> jcmbDrinks;
    private javax.swing.JLabel jlblCostOfDelivery;
    private javax.swing.JLabel jlblCostOfDrinks;
    private javax.swing.JLabel jlblCostOfMeal;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JTextField jtxtChickBiri;
    private javax.swing.JTextField jtxtChickBurger;
    private javax.swing.JTextField jtxtChickPizza;
    private javax.swing.JTextField jtxtChickenMomo;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtFriedRice;
    private javax.swing.JTextField jtxtGrillNun;
    private javax.swing.JTextField jtxtLemonRice;
    private javax.swing.JTextField jtxtMuttonBiri;
    private javax.swing.JTextField jtxtOvenBakedPasta;
    private javax.swing.JTextField jtxtPotatoWed;
    private javax.swing.JTextArea jtxtReceipt;
    // End of variables declaration//GEN-END:variables
}
